In [23]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [24]:
df = pd.read_csv('Advertising.csv')

In [25]:
X = df.drop('sales', axis = 1)
y = df['sales']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [26]:
from sklearn.linear_model import Ridge

In [27]:
from sklearn.model_selection import cross_validate

In [28]:
model = Ridge(alpha = 100)

In [29]:
scores = cross_validate(model, X_train, y_train, scoring = ['neg_mean_squared_error','neg_mean_absolute_error'], cv = 10)

In [30]:
scores = pd.DataFrame(scores)

In [31]:
scores.mean()

fit_time                        0.001624
score_time                      0.001758
test_neg_mean_squared_error    -7.565121
test_neg_mean_absolute_error   -2.083773
dtype: float64

In [32]:
model = Ridge(alpha = 1)

In [33]:
scores = cross_validate(model, X_train, y_train, scoring = ['neg_mean_squared_error','neg_mean_absolute_error'], cv = 10)

In [34]:
scores = pd.DataFrame(scores)

In [35]:
scores.mean()

fit_time                        0.001889
score_time                      0.001585
test_neg_mean_squared_error    -3.323018
test_neg_mean_absolute_error   -1.308467
dtype: float64

In [36]:
model.fit(X_train, y_train)

Ridge(alpha=1)

In [37]:
y_final_pred = model.predict(X_test)

In [40]:
from sklearn.metrics import mean_squared_error

In [41]:
mean_squared_error(y_test,y_final_pred)

2.319021579428752